import { addDays, subDays } from "date-fns";

export interface Room {
  id: string;
  name: string;
  type: "room" | "dorm";
  beds: number;
  pmsStatus: "mapped" | "unmapped";
  pmsId: string | null;
  ttlockId?: string | null;
  battery: number; // percentage
  floor?: string;
  ordering?: number;
  commonAreas: string[]; // IDs of linked common areas
  isDreamBoks?: boolean;
  spaceCategory?: string | null;
  label?: string | null;
}

export interface CommonArea {
  id: string;
  name: string;
  battery: number;
  ttlockId?: string | null;
  floor?: string;
  building?: string;
  accessScope?: "universal" | "building" | "floor" | "manual";
}

export interface Pin {
  id: string;
  roomId: string; // or bedId
  type: "guest" | "staff" | "cleaner" | "service";
  code: string;
  name: string; // Guest name or Staff name
  email?: string;
  validFrom: string;
  validTo: string;
  status: "active" | "expired" | "pending" | "error";
  doors: string[]; // Names of doors this PIN opens
  assigner?: string;
  assigningTime?: string;
}

export interface Log {
  id: string;
  timestamp: string;
  level: "info" | "warning" | "error";
  message: string;
  source: "MEWS" | "TTLock" | "System";
}

export interface Reservation {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  arrival: string;
  departure: string;
  pmsId: string;
  extId: string; // The "0" or other ID shown in screenshot
  adults: number;
  children: number;
  status: "Confirmed" | "Canceled" | "Checked-in" | "Checked-out";
  room?: string;
  bed?: string;
  price?: string;
  currency?: string;
  owing?: string;
  mobile?: string;
  confirmationCode?: string;
  generatedPin?: string | null;
  roomId?: string | null;
  groupName?: string | null;
  requestedCategory?: string | null;
  spaceCategory?: string | null;
  assignedSpace?: string | null;
  rateName?: string | null;
  avgRate?: string | null;
  totalAmount?: string | null;
  origin?: string | null;
  reservationSource?: string | null;
  pmsCheckinSource?: string | null;
  pinStatus?: string | null;
  pinFirstUsedAt?: string | null;
  preCheckinStatus?: string | null;
}

export interface ReservationLog {
  id: string;
  reservationId: string;
  message: string;
  timestamp: string;
  type: "email" | "sms" | "system" | "error";
  detail?: string;
}

export const mockReservationLogs: ReservationLog[] = [
  {
    id: "rl-1",
    reservationId: "res-1",
    message: "\"Checked-in\" email was delivered to",
    detail: "guest-one@example.com via Goki",
    timestamp: "2025-11-23 16:52",
    type: "email"
  },
  {
    id: "rl-2",
    reservationId: "res-1",
    message: "PIN 2994 was failed via Twilio from",
    detail: "+4500000001 to +4500000002",
    timestamp: "2025-11-23 16:52",
    type: "error"
  },
  {
    id: "rl-3",
    reservationId: "res-1",
    message: "\"Checked-in\" email was sent to",
    detail: "guest-one@example.com via Goki",
    timestamp: "2025-11-23 16:52",
    type: "email"
  },
  {
    id: "rl-4",
    reservationId: "res-1",
    message: "Access generated by System",
    timestamp: "2025-11-23 16:52",
    type: "system"
  },
  {
    id: "rl-5",
    reservationId: "res-1",
    message: "State changed from confirmed to started by mews",
    timestamp: "2025-11-23 16:52",
    type: "system"
  }
];

export interface QrCode {
  id: string;
  name: string;
  assigner: string;
  assigningTime: string;
  validityPeriod: string;
  status: "Valid" | "Expired";
}

export const mockQrCodes: QrCode[] = [
  {
    id: "qr-1",
    name: "sab",
    assigner: "je",
    assigningTime: "2025-11-08 15:59",
    validityPeriod: "Permanent",
    status: "Valid"
  },
  {
    id: "qr-2",
    name: "DWT",
    assigner: "ce",
    assigningTime: "2025-11-07 15:20",
    validityPeriod: "Permanent",
    status: "Valid"
  }
];

export const mockCommonAreas: CommonArea[] = [
  { id: "ca-212a", name: "212A", battery: 100, floor: "2" },
  { id: "ca-312a", name: "312A", battery: 100, floor: "3" },
  { id: "ca-412a", name: "412A", battery: 100, floor: "4" },
  { id: "ca-entrance", name: "Entrance 1. floor", battery: 100, floor: "1" },
  { id: "ca-backdoor", name: "Back door 1. floor", battery: 100, floor: "1" },
];

export interface LockDevice {
  id: string;
  name: string;
  mac: string;
  battery: number;
  isLinked: boolean;
}

export const mockLockDevices: LockDevice[] = [
  { id: "l-101", name: "101", mac: "AA:BB:CC:00:01", battery: 95, isLinked: true },
  { id: "l-102", name: "102", mac: "AA:BB:CC:00:02", battery: 92, isLinked: true },
  { id: "l-103", name: "103", mac: "AA:BB:CC:00:03", battery: 88, isLinked: true },
  { id: "l-104", name: "104", mac: "AA:BB:CC:00:04", battery: 90, isLinked: true },
  { id: "l-105", name: "105", mac: "AA:BB:CC:00:05", battery: 85, isLinked: true },
  { id: "l-212a", name: "212A", mac: "AA:BB:CC:00:06", battery: 100, isLinked: true },
  { id: "l-entrance", name: "Entrance 1. floor", mac: "AA:BB:CC:00:07", battery: 100, isLinked: true },
  // Unmapped locks for demo
  { id: "l-205", name: "205", mac: "AA:BB:CC:00:08", battery: 100, isLinked: false },
  { id: "l-kitchen", name: "Staff Kitchen", mac: "AA:BB:CC:00:09", battery: 98, isLinked: false },
];

export const mockRooms: Room[] = [
  {
    id: "r-101",
    name: "101",
    type: "dorm",
    beds: 4,
    pmsStatus: "mapped",
    pmsId: "101",
    battery: 100,
    floor: "1",
    ordering: 101,
    commonAreas: ["ca-entrance"],
    isDreamBoks: true,
  },
  {
    id: "r-102",
    name: "102",
    type: "room",
    beds: 1,
    pmsStatus: "mapped",
    pmsId: "102",
    battery: 100,
    floor: "1",
    ordering: 102,
    commonAreas: [],
    isDreamBoks: true,
  },
  {
    id: "r-103",
    name: "103",
    type: "room",
    beds: 1,
    pmsStatus: "mapped",
    pmsId: "103",
    battery: 100,
    floor: "1",
    ordering: 103,
    commonAreas: [],
    isDreamBoks: false,
  },
  {
    id: "r-104",
    name: "104",
    type: "room",
    beds: 1,
    pmsStatus: "mapped",
    pmsId: "104",
    battery: 100,
    floor: "1",
    ordering: 104,
    commonAreas: [],
    isDreamBoks: true,
  },
  {
    id: "r-105",
    name: "105",
    type: "room",
    beds: 1,
    pmsStatus: "mapped",
    pmsId: "105",
    battery: 100,
    floor: "1",
    ordering: 105,
    commonAreas: [],
    isDreamBoks: false,
  },
];

export const mockPins: Pin[] = [
  {
    id: "p-1",
    roomId: "r-101",
    type: "guest",
    code: "482910",
    name: "Alice Johnson",
    email: "alice@example.com",
    validFrom: new Date().toISOString(),
    validTo: addDays(new Date(), 2).toISOString(),
    status: "active",
    doors: ["101", "Main Entrance", "Kitchen"],
    assigner: "je",
    assigningTime: subDays(new Date(), 1).toISOString(),
  },
  {
    id: "p-2",
    roomId: "r-112A",
    type: "guest",
    code: "992811",
    name: "Bob Smith",
    email: "bob@example.com",
    validFrom: subDays(new Date(), 1).toISOString(),
    validTo: addDays(new Date(), 1).toISOString(),
    status: "active",
    doors: ["112A", "Main Entrance", "Back Door"],
    assigner: "ce",
    assigningTime: subDays(new Date(), 2).toISOString(),
  },
  {
    id: "p-3",
    roomId: "r-101",
    type: "cleaner",
    code: "112233",
    name: "Housekeeping",
    validFrom: new Date().toISOString(),
    validTo: addDays(new Date(), 30).toISOString(),
    status: "active",
    doors: ["101"],
    assigner: "ce",
    assigningTime: subDays(new Date(), 5).toISOString(),
  },
  {
    id: "p-4",
    roomId: "r-201",
    type: "guest",
    code: "000000",
    name: "Error User",
    validFrom: new Date().toISOString(),
    validTo: addDays(new Date(), 1).toISOString(),
    status: "error",
    doors: ["201"],
    assigner: "System",
    assigningTime: new Date().toISOString(),
  },
];

export const mockLogs: Log[] = [
  {
    id: "l-1",
    timestamp: new Date().toISOString(),
    level: "info",
    message: "PIN generated for reservation #99281",
    source: "System",
  },
  {
    id: "l-2",
    timestamp: subDays(new Date(), 0.1).toISOString(),
    level: "error",
    message: "Failed to sync lock status for Room 201",
    source: "TTLock",
  },
  {
    id: "l-3",
    timestamp: subDays(new Date(), 0.2).toISOString(),
    level: "info",
    message: "Webhook received: Checked-in (Res #12345)",
    source: "MEWS",
  },
];

export const mockReservations: Reservation[] = [
  {
    id: "res-1",
    email: "anna.andersen@example.com",
    firstName: "Anna",
    lastName: "Andersen",
    arrival: new Date().toISOString(),
    departure: addDays(new Date(), 3).toISOString(),
    pmsId: "90001",
    extId: "0",
    adults: 1,
    children: 0,
    status: "Confirmed",
    room: "602",
    bed: "bed 1",
    price: "3,798",
    currency: "DKK",
    mobile: "+4917682979661",
    confirmationCode: "44764"
  },
  {
    id: "res-2",
    email: "anna.andersen@example.com",
    firstName: "Anna",
    lastName: "Andersen",
    arrival: new Date().toISOString(),
    departure: addDays(new Date(), 3).toISOString(),
    pmsId: "90002",
    extId: "0",
    adults: 1,
    children: 0,
    status: "Confirmed",
    room: "602",
    bed: "bed 1"
  },
  {
    id: "res-3",
    email: "ben.bergstrom@example.com",
    firstName: "BEN",
    lastName: "BERGSTRÖM",
    arrival: new Date().toISOString(),
    departure: addDays(new Date(), 1).toISOString(),
    pmsId: "90003",
    extId: "0",
    adults: 1,
    children: 0,
    status: "Confirmed",
    room: "112A",
  },
  {
    id: "res-4",
    email: "carl.clausen@example.com",
    firstName: "Carl",
    lastName: "Clausen",
    arrival: new Date().toISOString(),
    departure: addDays(new Date(), 1).toISOString(),
    pmsId: "90004",
    extId: "0",
    adults: 2,
    children: 0,
    status: "Confirmed",
    room: "201",
  },
  {
    id: "res-5",
    email: "ddahl.000001@guest.booking.com",
    firstName: "Dana",
    lastName: "Dahl",
    arrival: addDays(new Date(), 60).toISOString(),
    departure: addDays(new Date(), 67).toISOString(),
    pmsId: "90005",
    extId: "0",
    adults: 1,
    children: 0,
    status: "Canceled",
  },
  {
    id: "res-6",
    email: "eeriksen.000002@guest.booking.com",
    firstName: "Emi",
    lastName: "Eriksen",
    arrival: addDays(new Date(), 20).toISOString(),
    departure: addDays(new Date(), 21).toISOString(),
    pmsId: "43778",
    extId: "0",
    adults: 1,
    children: 0,
    status: "Canceled",
  }
];
